base_url: "https://openrouter.ai/api/v1"
request_config:
    model: "openai/gpt-4.1"
    response_format:
        type: json_schema
        json_schema:
            name: query_output
            strict: true
            schema:
                type: object
                properties:
                    query:
                        type: string
                        description: Query written un natural language to retrieve a lemma/theorem etc.
                required:
                    - query
                additionalProperties: false